site_name: Tikebit
pages:
  - TKB: tkb.md
  - TEUR: teur.md
  - Vesting: vesting.md
  - Ownable: ownable.md
  - Interfaces y librerías: interface.md

theme: 
  name: material
  highlightjs: true
  hljs_languages:
    - solidity
